# ============================================================
# SCRIPT 32B — ChEMBL ANNOTATION QC
# HER2+ Luminal Breast Cancer Drug Repurposing
#
# Purpose:
#   Quality-control the ChEMBL annotations generated by
#   Script 32.
#
# This script DOES NOT:
#   - change LINCS connectivity scores
#   - change candidate ranks
#   - remove candidates
#   - assign final biological relevance
#
# It identifies:
#   1. exact vs review-required ChEMBL mappings
#   2. duplicate ChEMBL assignments
#   3. compounds without mechanism records
#   4. mechanism / target records
#   5. candidates requiring manual identity review
# ============================================================

suppressPackageStartupMessages({
    library(readr)
    library(dplyr)
})

cat("==============================================\n")
cat("SCRIPT 32B — ChEMBL ANNOTATION QC\n")
cat("==============================================\n\n")


# ------------------------------------------------------------
# 1. PATHS
# ------------------------------------------------------------

base_dir <- "results/drug_repurposing/LINCS_HER2_Luminal"

identity_file <- file.path(
    base_dir,
    "HER2_Luminal_ChEMBL_compound_identity.csv"
)

mechanism_file <- file.path(
    base_dir,
    "HER2_Luminal_ChEMBL_mechanisms.csv"
)

candidate_file <- file.path(
    base_dir,
    "HER2_Luminal_candidate_mechanism_annotation.csv"
)

out_dir <- base_dir


# ------------------------------------------------------------
# 2. CHECK FILES
# ------------------------------------------------------------

required_files <- c(
    identity_file,
    mechanism_file,
    candidate_file
)

missing_files <- required_files[
    !file.exists(required_files)
]

if (length(missing_files) > 0) {

    stop(
        "Missing Script 32 outputs:\n",
        paste(
            missing_files,
            collapse = "\n"
        )
    )

}


# ------------------------------------------------------------
# 3. LOAD DATA
# ------------------------------------------------------------

cat("Loading Script 32 outputs...\n\n")

identity <- read_csv(
    identity_file,
    show_col_types = FALSE
)

mechanisms <- read_csv(
    mechanism_file,
    show_col_types = FALSE
)

annotations <- read_csv(
    candidate_file,
    show_col_types = FALSE
)

cat(
    "Identity records:",
    nrow(identity),
    "\n"
)

cat(
    "Mechanism records:",
    nrow(mechanisms),
    "\n"
)

cat(
    "Candidate annotations:",
    nrow(annotations),
    "\n\n"
)


# ------------------------------------------------------------
# 4. IDENTITY STATUS QC
# ------------------------------------------------------------

cat("==============================================\n")
cat("IDENTITY MATCH QC\n")
cat("==============================================\n\n")

identity_status <- identity %>%

    count(
        match_status,
        name = "compounds"
    ) %>%

    arrange(
        desc(compounds)
    )

print(identity_status)

cat("\n")


# ------------------------------------------------------------
# 5. EXACT MATCHES
# ------------------------------------------------------------

exact_matches <- identity %>%

    filter(
        match_status == "exact_name_match"
    ) %>%

    select(
        pert_id,
        pert_iname,
        chembl_id,
        pref_name,
        max_phase,
        match_status
    )

cat("Exact identity matches:", nrow(exact_matches), "\n\n")

write_csv(
    exact_matches,
    file.path(
        out_dir,
        "SCRIPT32B_exact_ChEMBL_matches.csv"
    )
)


# ------------------------------------------------------------
# 6. REVIEW-REQUIRED MATCHES
# ------------------------------------------------------------

review_matches <- identity %>%

    filter(
        match_status != "exact_name_match"
    ) %>%

    select(
        pert_id,
        pert_iname,
        chembl_id,
        pref_name,
        max_phase,
        match_status
    ) %>%

    arrange(
        pert_iname
    )

cat("==============================================\n")
cat("IDENTITY MATCHES REQUIRING REVIEW\n")
cat("==============================================\n\n")

cat(
    "Candidates requiring review:",
    nrow(review_matches),
    "\n\n"
)

print(
    review_matches,
    n = Inf
)

write_csv(
    review_matches,
    file.path(
        out_dir,
        "SCRIPT32B_ChEMBL_identity_review_required.csv"
    )
)


# ------------------------------------------------------------
# 7. DUPLICATE ChEMBL IDS
# ------------------------------------------------------------

cat("\n==============================================\n")
cat("DUPLICATE ChEMBL ID QC\n")
cat("==============================================\n\n")

duplicate_ids <- identity %>%

    filter(
        !is.na(chembl_id)
    ) %>%

    group_by(
        chembl_id
    ) %>%

    summarise(

        n_LINCS_compounds =
            n_distinct(pert_id),

        LINCS_compounds =
            paste(
                unique(pert_iname),
                collapse = "; "
            ),

        LINCS_ids =
            paste(
                unique(pert_id),
                collapse = "; "
            ),

        .groups = "drop"

    ) %>%

    filter(
        n_LINCS_compounds > 1
    )

if (nrow(duplicate_ids) == 0) {

    cat(
        "No duplicate ChEMBL assignments detected.\n"
    )

} else {

    cat(
        "Duplicate ChEMBL assignments:",
        nrow(duplicate_ids),
        "\n\n"
    )

    print(
        duplicate_ids,
        n = Inf
    )

}

write_csv(
    duplicate_ids,
    file.path(
        out_dir,
        "SCRIPT32B_duplicate_ChEMBL_assignments.csv"
    )
)


# ------------------------------------------------------------
# 8. MECHANISM COVERAGE
# ------------------------------------------------------------

cat("\n==============================================\n")
cat("MECHANISM COVERAGE\n")
cat("==============================================\n\n")

all_chembl <- identity %>%

    filter(
        !is.na(chembl_id)
    ) %>%

    distinct(
        chembl_id
    )

mechanism_chembl <- mechanisms %>%

    filter(
        !is.na(chembl_id)
    ) %>%

    distinct(
        chembl_id
    )

no_mechanism <- all_chembl %>%

    anti_join(
        mechanism_chembl,
        by = "chembl_id"
    )

cat(
    "Unique ChEMBL compounds:",
    nrow(all_chembl),
    "\n"
)

cat(
    "With mechanism records:",
    nrow(mechanism_chembl),
    "\n"
)

cat(
    "Without mechanism records:",
    nrow(no_mechanism),
    "\n\n"
)


# ------------------------------------------------------------
# 9. CANDIDATES WITHOUT MECHANISM
# ------------------------------------------------------------

no_mechanism_candidates <- identity %>%

    filter(
        chembl_id %in%
            no_mechanism$chembl_id
    ) %>%

    select(
        pert_id,
        pert_iname,
        chembl_id,
        pref_name,
        match_status
    ) %>%

    arrange(
        pert_iname
    )

cat("Candidates without mechanism records:\n\n")

print(
    no_mechanism_candidates,
    n = Inf
)

write_csv(
    no_mechanism_candidates,
    file.path(
        out_dir,
        "SCRIPT32B_candidates_without_mechanism.csv"
    )
)


# ------------------------------------------------------------
# 10. MECHANISM / TARGET QC
# ------------------------------------------------------------

cat("\n==============================================\n")
cat("MECHANISM / TARGET RECORDS\n")
cat("==============================================\n\n")

mechanism_qc <- mechanisms %>%

    select(
        chembl_id,
        target_chembl_id,
        mechanism_of_action,
        action_type,
        mechanism_status
    ) %>%

    distinct()

cat(
    "Mechanism-target records:",
    nrow(mechanism_qc),
    "\n\n"
)

print(
    mechanism_qc,
    n = Inf
)

write_csv(
    mechanism_qc,
    file.path(
        out_dir,
        "SCRIPT32B_mechanism_target_QC.csv"
    )
)


# ------------------------------------------------------------
# 11. MECHANISM STATUS
# ------------------------------------------------------------

cat("\n==============================================\n")
cat("MECHANISM STATUS\n")
cat("==============================================\n\n")

print(
    table(
        mechanisms$mechanism_status,
        useNA = "ifany"
    )
)


# ------------------------------------------------------------
# 12. ACTION TYPES
# ------------------------------------------------------------

cat("\n==============================================\n")
cat("ACTION TYPES\n")
cat("==============================================\n\n")

action_table <- mechanisms %>%

    count(
        action_type,
        sort = TRUE
    )

print(
    action_table,
    n = Inf
)

write_csv(
    action_table,
    file.path(
        out_dir,
        "SCRIPT32B_action_type_summary.csv"
    )
)


# ------------------------------------------------------------
# 13. COMPOUND-LEVEL QC TABLE
# ------------------------------------------------------------

cat("\n==============================================\n")
cat("COMPOUND-LEVEL QC TABLE\n")
cat("==============================================\n\n")

mechanism_counts <- mechanisms %>%

    filter(
        !is.na(chembl_id)
    ) %>%

    group_by(
        chembl_id
    ) %>%

    summarise(

        mechanism_records =
            n(),

        target_count =
            n_distinct(
                target_chembl_id,
                na.rm = TRUE
            ),

        mechanism_status =
            paste(
                unique(
                    mechanism_status
                ),
                collapse = ";"
            ),

        .groups = "drop"

    )

compound_qc <- identity %>%

    left_join(
        mechanism_counts,
        by = "chembl_id"
    ) %>%

    mutate(

        mechanism_records =
            ifelse(
                is.na(mechanism_records),
                0,
                mechanism_records
            ),

        target_count =
            ifelse(
                is.na(target_count),
                0,
                target_count
            ),

        mechanism_annotation_status =
            ifelse(
                mechanism_records > 0,
                "mechanism_found",
                "no_mechanism_record"
            )

    ) %>%

    select(
        pert_id,
        pert_iname,
        chembl_id,
        pref_name,
        max_phase,
        match_status,
        mechanism_records,
        target_count,
        mechanism_annotation_status
    ) %>%

    arrange(
        desc(
            mechanism_records
        ),
        pert_iname
    )

write_csv(
    compound_qc,
    file.path(
        out_dir,
        "SCRIPT32B_compound_level_QC.csv"
    )
)


# ------------------------------------------------------------
# 14. FINAL QC SUMMARY
# ------------------------------------------------------------

n_candidates <- nrow(
    identity
)

n_exact <- sum(
    identity$match_status ==
        "exact_name_match",
    na.rm = TRUE
)

n_review <- sum(
    identity$match_status ==
        "search_match_requires_review",
    na.rm = TRUE
)

n_unique_chembl <- n_distinct(
    identity$chembl_id[
        !is.na(identity$chembl_id)
    ]
)

n_duplicate_chembl <- nrow(
    duplicate_ids
)

n_with_mechanism <- nrow(
    mechanism_chembl
)

n_without_mechanism <- nrow(
    no_mechanism
)


summary_df <- data.frame(

    candidates =
        n_candidates,

    exact_identity_matches =
        n_exact,

    identity_matches_requiring_review =
        n_review,

    unique_chembl_compounds =
        n_unique_chembl,

    duplicate_chembl_assignments =
        n_duplicate_chembl,

    compounds_with_mechanism =
        n_with_mechanism,

    compounds_without_mechanism =
        n_without_mechanism,

    mechanism_target_records =
        nrow(mechanisms)

)

write_csv(
    summary_df,
    file.path(
        out_dir,
        "SCRIPT32B_QC_summary.csv"
    )
)


# ------------------------------------------------------------
# 15. FINAL REPORT
# ------------------------------------------------------------

cat("\n==============================================\n")
cat("SCRIPT 32B COMPLETE\n")
cat("==============================================\n\n")

cat(
    "Candidates:",
    n_candidates,
    "\n"
)

cat(
    "Exact ChEMBL identities:",
    n_exact,
    "\n"
)

cat(
    "Identities requiring review:",
    n_review,
    "\n"
)

cat(
    "Unique ChEMBL compounds:",
    n_unique_chembl,
    "\n"
)

cat(
    "Duplicate ChEMBL assignments:",
    n_duplicate_chembl,
    "\n"
)

cat(
    "Compounds with mechanism:",
    n_with_mechanism,
    "\n"
)

cat(
    "Compounds without mechanism:",
    n_without_mechanism,
    "\n"
)

cat(
    "Mechanism-target records:",
    nrow(mechanisms),
    "\n\n"
)

cat(
    "Output directory:\n",
    out_dir,
    "\n\n"
)

cat("KEY OUTPUTS:\n\n")

cat(
    "1. SCRIPT32B_ChEMBL_identity_review_required.csv\n"
)

cat(
    "2. SCRIPT32B_duplicate_ChEMBL_assignments.csv\n"
)

cat(
    "3. SCRIPT32B_candidates_without_mechanism.csv\n"
)

cat(
    "4. SCRIPT32B_mechanism_target_QC.csv\n"
)

cat(
    "5. SCRIPT32B_compound_level_QC.csv\n"
)

cat(
    "6. SCRIPT32B_QC_summary.csv\n\n"
)

cat(
    "IMPORTANT:\n"
)

cat(
    "No candidate was removed or re-ranked.\n"
)

cat(
    "Identity uncertainty is explicitly retained.\n\n"
)

cat(
    "NEXT STEP:\n"
)

cat(
    "Review Script 32B output before Script 33.\n"
)